version: '3'

services:
  node:
    build: 
      context: .
      dockerfile: dockerfile-nodejs
    ports:
      - "8765:8765"
    restart: always
  ngnix:
    image: nginx:stable
    ports:
      - "2121:80"
    restart: always
    volumes:
      - ./src:/usr/share/nginx/html
    depends_on:
      - node
  nginx_tap:
    image: nginx:stable
    ports:
      - "2209:80"
    restart: always
    volumes:
      - ./public:/usr/share/nginx/html
    depends_on:
      - node